name: pakistan_offline_map_explorer
description: Pakistan Offline Map Explorer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  dart_osmpbf: ^0.0.1
  flutter:
    sdk: flutter
  flutter_map: ^8.3.0
  geolocator: ^14.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets_web/places_index.json
