name: pakistan_offline_map_explorer
description: Pakistan Offline Map Explorer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  flutter_map: ^8.3.0
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  sqlite3: ^2.9.4
  sqlite3_flutter_libs: ^0.5.24
  vector_tile: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets_web/places_index.json
